/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AddSubscriberResult = { 'ok' : SubscriberView } |
  { 'err' : string };
export type CampaignId = bigint;
export type CampaignStatus = { 'sent' : null } |
  { 'draft' : null };
export interface CampaignView {
  'id' : CampaignId,
  'status' : CampaignStatus,
  'subject' : string,
  'body' : string,
  'name' : string,
  'sentAt' : [] | [Timestamp],
  'senderName' : string,
  'recipientCount' : bigint,
}
export type CreateCampaignResult = { 'ok' : CampaignView } |
  { 'err' : string };
export interface DashboardStats {
  'lastCampaign' : [] | [CampaignView],
  'activeSubscribers' : bigint,
  'totalCampaignsSent' : bigint,
  'totalSubscribers' : bigint,
}
export type SendCampaignResult = { 'ok' : null } |
  { 'err' : string };
export type SubscriberId = bigint;
export type SubscriberStatus = { 'unsubscribed' : null } |
  { 'subscribed' : null };
export interface SubscriberView {
  'id' : SubscriberId,
  'status' : SubscriberStatus,
  'name' : string,
  'email' : string,
  'dateAdded' : Timestamp,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'addSubscriber' : ActorMethod<[string, string], AddSubscriberResult>,
  'bulkImportSubscribers' : ActorMethod<
    [Array<[string, string]>],
    { 'imported' : bigint, 'skipped' : bigint }
  >,
  'createCampaign' : ActorMethod<
    [string, string, string, string],
    CreateCampaignResult
  >,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'listCampaigns' : ActorMethod<[], Array<CampaignView>>,
  'listSubscribers' : ActorMethod<[], Array<SubscriberView>>,
  'sendCampaign' : ActorMethod<[bigint], SendCampaignResult>,
  'toggleSubscriberStatus' : ActorMethod<[bigint], [] | [SubscriberView]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];