/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubscriberId = IDL.Nat;
export const SubscriberStatus = IDL.Variant({
  'unsubscribed' : IDL.Null,
  'subscribed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const SubscriberView = IDL.Record({
  'id' : SubscriberId,
  'status' : SubscriberStatus,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'dateAdded' : Timestamp,
});
export const AddSubscriberResult = IDL.Variant({
  'ok' : SubscriberView,
  'err' : IDL.Text,
});
export const CampaignId = IDL.Nat;
export const CampaignStatus = IDL.Variant({
  'sent' : IDL.Null,
  'draft' : IDL.Null,
});
export const CampaignView = IDL.Record({
  'id' : CampaignId,
  'status' : CampaignStatus,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'name' : IDL.Text,
  'sentAt' : IDL.Opt(Timestamp),
  'senderName' : IDL.Text,
  'recipientCount' : IDL.Nat,
});
export const CreateCampaignResult = IDL.Variant({
  'ok' : CampaignView,
  'err' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'lastCampaign' : IDL.Opt(CampaignView),
  'activeSubscribers' : IDL.Nat,
  'totalCampaignsSent' : IDL.Nat,
  'totalSubscribers' : IDL.Nat,
});
export const SendCampaignResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'addSubscriber' : IDL.Func([IDL.Text, IDL.Text], [AddSubscriberResult], []),
  'bulkImportSubscribers' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [IDL.Record({ 'imported' : IDL.Nat, 'skipped' : IDL.Nat })],
      [],
    ),
  'createCampaign' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [CreateCampaignResult],
      [],
    ),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'listCampaigns' : IDL.Func([], [IDL.Vec(CampaignView)], ['query']),
  'listSubscribers' : IDL.Func([], [IDL.Vec(SubscriberView)], ['query']),
  'sendCampaign' : IDL.Func([IDL.Nat], [SendCampaignResult], []),
  'toggleSubscriberStatus' : IDL.Func([IDL.Nat], [IDL.Opt(SubscriberView)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubscriberId = IDL.Nat;
  const SubscriberStatus = IDL.Variant({
    'unsubscribed' : IDL.Null,
    'subscribed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const SubscriberView = IDL.Record({
    'id' : SubscriberId,
    'status' : SubscriberStatus,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'dateAdded' : Timestamp,
  });
  const AddSubscriberResult = IDL.Variant({
    'ok' : SubscriberView,
    'err' : IDL.Text,
  });
  const CampaignId = IDL.Nat;
  const CampaignStatus = IDL.Variant({ 'sent' : IDL.Null, 'draft' : IDL.Null });
  const CampaignView = IDL.Record({
    'id' : CampaignId,
    'status' : CampaignStatus,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'name' : IDL.Text,
    'sentAt' : IDL.Opt(Timestamp),
    'senderName' : IDL.Text,
    'recipientCount' : IDL.Nat,
  });
  const CreateCampaignResult = IDL.Variant({
    'ok' : CampaignView,
    'err' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'lastCampaign' : IDL.Opt(CampaignView),
    'activeSubscribers' : IDL.Nat,
    'totalCampaignsSent' : IDL.Nat,
    'totalSubscribers' : IDL.Nat,
  });
  const SendCampaignResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  
  return IDL.Service({
    'addSubscriber' : IDL.Func([IDL.Text, IDL.Text], [AddSubscriberResult], []),
    'bulkImportSubscribers' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [IDL.Record({ 'imported' : IDL.Nat, 'skipped' : IDL.Nat })],
        [],
      ),
    'createCampaign' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [CreateCampaignResult],
        [],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'listCampaigns' : IDL.Func([], [IDL.Vec(CampaignView)], ['query']),
    'listSubscribers' : IDL.Func([], [IDL.Vec(SubscriberView)], ['query']),
    'sendCampaign' : IDL.Func([IDL.Nat], [SendCampaignResult], []),
    'toggleSubscriberStatus' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SubscriberView)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };