/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type AddSubscriberResult = {
    __kind__: "ok";
    ok: SubscriberView;
} | {
    __kind__: "err";
    err: string;
};
export type CreateCampaignResult = {
    __kind__: "ok";
    ok: CampaignView;
} | {
    __kind__: "err";
    err: string;
};
export type SendCampaignResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface CampaignView {
    id: CampaignId;
    status: CampaignStatus;
    subject: string;
    body: string;
    name: string;
    sentAt?: Timestamp;
    senderName: string;
    recipientCount: bigint;
}
export type CampaignId = bigint;
export interface DashboardStats {
    lastCampaign?: CampaignView;
    activeSubscribers: bigint;
    totalCampaignsSent: bigint;
    totalSubscribers: bigint;
}
export type SubscriberId = bigint;
export interface SubscriberView {
    id: SubscriberId;
    status: SubscriberStatus;
    name: string;
    email: string;
    dateAdded: Timestamp;
}
export enum CampaignStatus {
    sent = "sent",
    draft = "draft"
}
export enum SubscriberStatus {
    unsubscribed = "unsubscribed",
    subscribed = "subscribed"
}
export interface backendInterface {
    addSubscriber(name: string, email: string): Promise<AddSubscriberResult>;
    bulkImportSubscribers(entries: Array<[string, string]>): Promise<{
        imported: bigint;
        skipped: bigint;
    }>;
    createCampaign(name: string, subject: string, senderName: string, body: string): Promise<CreateCampaignResult>;
    getDashboardStats(): Promise<DashboardStats>;
    listCampaigns(): Promise<Array<CampaignView>>;
    listSubscribers(): Promise<Array<SubscriberView>>;
    sendCampaign(id: bigint): Promise<SendCampaignResult>;
    toggleSubscriberStatus(id: bigint): Promise<SubscriberView | null>;
}
import type { AddSubscriberResult as _AddSubscriberResult, CampaignId as _CampaignId, CampaignStatus as _CampaignStatus, CampaignView as _CampaignView, CreateCampaignResult as _CreateCampaignResult, DashboardStats as _DashboardStats, SendCampaignResult as _SendCampaignResult, SubscriberId as _SubscriberId, SubscriberStatus as _SubscriberStatus, SubscriberView as _SubscriberView, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addSubscriber(arg0: string, arg1: string): Promise<AddSubscriberResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubscriber(arg0, arg1);
                return from_candid_AddSubscriberResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubscriber(arg0, arg1);
            return from_candid_AddSubscriberResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async bulkImportSubscribers(arg0: Array<[string, string]>): Promise<{
        imported: bigint;
        skipped: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportSubscribers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportSubscribers(arg0);
            return result;
        }
    }
    async createCampaign(arg0: string, arg1: string, arg2: string, arg3: string): Promise<CreateCampaignResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createCampaign(arg0, arg1, arg2, arg3);
                return from_candid_CreateCampaignResult_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCampaign(arg0, arg1, arg2, arg3);
            return from_candid_CreateCampaignResult_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return from_candid_DashboardStats_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return from_candid_DashboardStats_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCampaigns(): Promise<Array<CampaignView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCampaigns();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCampaigns();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSubscribers(): Promise<Array<SubscriberView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubscribers();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubscribers();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendCampaign(arg0: bigint): Promise<SendCampaignResult> {
        if (this.processError) {
            try {
                const result = await this.actor.sendCampaign(arg0);
                return from_candid_SendCampaignResult_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendCampaign(arg0);
            return from_candid_SendCampaignResult_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleSubscriberStatus(arg0: bigint): Promise<SubscriberView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleSubscriberStatus(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleSubscriberStatus(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AddSubscriberResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AddSubscriberResult): AddSubscriberResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_CampaignStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CampaignStatus): CampaignStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_CampaignView_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CampaignView): CampaignView {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_CreateCampaignResult_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateCampaignResult): CreateCampaignResult {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardStats_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardStats): DashboardStats {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_SendCampaignResult_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SendCampaignResult): SendCampaignResult {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriberStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriberStatus): SubscriberStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriberView_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriberView): SubscriberView {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CampaignView]): CampaignView | null {
    return value.length === 0 ? null : from_candid_CampaignView_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubscriberView]): SubscriberView | null {
    return value.length === 0 ? null : from_candid_SubscriberView_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CampaignId;
    status: _CampaignStatus;
    subject: string;
    body: string;
    name: string;
    sentAt: [] | [_Timestamp];
    senderName: string;
    recipientCount: bigint;
}): {
    id: CampaignId;
    status: CampaignStatus;
    subject: string;
    body: string;
    name: string;
    sentAt?: Timestamp;
    senderName: string;
    recipientCount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_CampaignStatus_n11(_uploadFile, _downloadFile, value.status),
        subject: value.subject,
        body: value.body,
        name: value.name,
        sentAt: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.sentAt)),
        senderName: value.senderName,
        recipientCount: value.recipientCount
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastCampaign: [] | [_CampaignView];
    activeSubscribers: bigint;
    totalCampaignsSent: bigint;
    totalSubscribers: bigint;
}): {
    lastCampaign?: CampaignView;
    activeSubscribers: bigint;
    totalCampaignsSent: bigint;
    totalSubscribers: bigint;
} {
    return {
        lastCampaign: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.lastCampaign)),
        activeSubscribers: value.activeSubscribers,
        totalCampaignsSent: value.totalCampaignsSent,
        totalSubscribers: value.totalSubscribers
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SubscriberId;
    status: _SubscriberStatus;
    name: string;
    email: string;
    dateAdded: _Timestamp;
}): {
    id: SubscriberId;
    status: SubscriberStatus;
    name: string;
    email: string;
    dateAdded: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_SubscriberStatus_n5(_uploadFile, _downloadFile, value.status),
        name: value.name,
        email: value.email,
        dateAdded: value.dateAdded
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sent: null;
} | {
    draft: null;
}): CampaignStatus {
    return "sent" in value ? CampaignStatus.sent : "draft" in value ? CampaignStatus.draft : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SubscriberView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SubscriberView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_SubscriberView_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unsubscribed: null;
} | {
    subscribed: null;
}): SubscriberStatus {
    return "unsubscribed" in value ? SubscriberStatus.unsubscribed : "subscribed" in value ? SubscriberStatus.subscribed : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CampaignView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CampaignView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_CampaignView_n9(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CampaignView>): Array<CampaignView> {
    return value.map((x)=>from_candid_CampaignView_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubscriberView>): Array<SubscriberView> {
    return value.map((x)=>from_candid_SubscriberView_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
